
package com.gafis.xj.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CheckServiceImplService", targetNamespace = "http://webservice.xj.gafis.com", wsdlLocation = "http://localhost:10008/xj/check/checkService?wsdl")
public class CheckServiceImplService
    extends Service
{

    private final static URL CHECKSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHECKSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CHECKSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.xj.gafis.com", "CheckServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10008/xj/check/checkService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHECKSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CHECKSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CheckServiceImplService() {
        super(__getWsdlLocation(), CHECKSERVICEIMPLSERVICE_QNAME);
    }

    public CheckServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECKSERVICEIMPLSERVICE_QNAME, features);
    }

    public CheckServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CHECKSERVICEIMPLSERVICE_QNAME);
    }

    public CheckServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECKSERVICEIMPLSERVICE_QNAME, features);
    }

    public CheckServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckService
     */
    @WebEndpoint(name = "CheckServicePort")
    public CheckService getCheckServicePort() {
        return super.getPort(new QName("http://webservice.xj.gafis.com", "CheckServicePort"), CheckService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckService
     */
    @WebEndpoint(name = "CheckServicePort")
    public CheckService getCheckServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.xj.gafis.com", "CheckServicePort"), CheckService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECKSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CHECKSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CHECKSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
