
package com.gafis.xj.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CheckService", targetNamespace = "http://webservice.xj.gafis.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "String", targetNamespace = "")
    @RequestWrapper(localName = "check", targetNamespace = "http://webservice.xj.gafis.com", className = "com.gafis.xj.webservice.Check")
    @ResponseWrapper(localName = "checkResponse", targetNamespace = "http://webservice.xj.gafis.com", className = "com.gafis.xj.webservice.CheckResponse")
    public String check(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
